base_url = "https://4yuinfo.github.io/zola-theme_jiufen/"
default_language = "zh-Hant-TW"
title = "Jiufen"
description = ""
compile_sass = false
minify_html = false
build_search_index = true
generate_feeds = true
generate_sitemap = true
generate_robots_txt = true
#travel="jiufen"

taxonomies = [
    {name = "tags", feed = true, paginate_by = 10 },
]

[slugify]
taxonomies = "safe"

[markdown]
highlight_code = true
error_on_missing_highlight = false
#highlight_theme = "material-dark"
#highlight_theme = "one-dark"
#highlight_theme = "railsbase16-green-screen-dark"
highlight_theme = "solarized-dark"
#highlight_theme = "nord"
render_emoji = true
smart_punctuation = true
definition_list = true
lazy_async_image = false
bottom_footnotes = false
insert_anchor_links = "none"

[search]
include_title = true
include_content = true
include_description = true
include_date = false
include_path = false
index_format = "fuse_javascript"

[extra]
site_name = '<img src="https://4yuinfo.github.io/zola-theme_jiufen/images/header001.png" width="100%")'
site_desc = "Welcome to the Zola Theme Jiufen introduction website."
copyright = "Copyright © 2025 Jiufen All rights reserved."
navigation_display_top = true
navigation_display_sidebar = true
navigation = [
    {name = '<i class="fa fa-home"></i>', url = "/", top=true, sitebar=false },
    {name = "Theme", url = "/theme/", top=true, sitebar=true },
    {name = "Travel", url = "/travel/", top=true, sitebar=true },
    {name = "404", url = "/404/", top=true, sitebar=false },
    {name = '<i class="fa-brands fa-github"></i> GitHub', url = "https://github.com/4yuinfo/zola-theme_jiufen", top=false, sitebar=true },
]
