base_url = "https://4yuinfo.github.io/zola-theme_jiufen/"
default_language = "zh-Hant-TW"
title = "Jiufen"
description = ""
compile_sass = false
minify_html = false
build_search_index = true
generate_feeds = true
generate_sitemap = true
generate_robots_txt = true
#travel="jiufen"

taxonomies = [
    {name = "tags", feed = true, paginate_by = 10 },
]

[slugify]
taxonomies = "safe"

[markdown]
highlight_code = true
error_on_missing_highlight = false
#highlight_theme = "material-dark"
#highlight_theme = "one-dark"
#highlight_theme = "railsbase16-green-screen-dark"
highlight_theme = "solarized-dark"
#highlight_theme = "nord"
render_emoji = true
smart_punctuation = true
definition_list = true
lazy_async_image = false
bottom_footnotes = false
insert_anchor_links = "none"

[search]
include_title = true
include_content = true
include_description = true
include_date = false
include_path = false
index_format = "fuse_javascript"

[extra]
site_name = '<img src="https://4yuinfo.github.io/zola-theme_jiufen/images/header001.png" width="100%">'
site_desc = "Welcome to the Zola Theme Jiufen introduction website."
copyright = "Copyright © 2025 Jiufen All rights reserved."

# Google Analytics (gtag.js)
# Set your GA4 Measurement ID to enable analytics, e.g., "G-XXXXXXXXXX"
# Leave empty or remove the line to disable.
# For privacy, you can anonymize IP addresses.
# Consent Mode: set `google_analytics_consent = true` to enable a built‑in consent banner.
# Optional: customize banner texts.
google_analytics_id = "G-MM9Z6T9SKE"
google_analytics_anonymize_ip = false
google_analytics_consent = true
google_analytics_consent_message = "This website uses cookies for statistics and to improve your experience. Do you agree to our use of Google Analytics?"
google_analytics_consent_accept_text = "Agree"
google_analytics_consent_decline_text = "DisAgree"

navigation_display_top = true
navigation_display_sidebar = true
navigation = [
    {name = '<i class="fa fa-home"></i>', url = "/", top=true, sidebar=false },
    {name = "Theme", url = "/theme/", top=true, sidebar=true },
    {name = "Travel", url = "/travel/", top=true, sidebar=true },
    {name = "404", url = "/404/", top=true, sidebar=false },
    {name = '<i class="fa-brands fa-github"></i> GitHub', url = "https://github.com/4yuinfo/zola-theme_jiufen", top=false, sidebar=true },
]
